services:
  manager:
    build: .
    container_name: manager
    hostname: manager
    command: ["/app/main", "1"]
    networks:
      lan:
        ipv4_address: 172.18.0.2

  participant1:
    build: .
    container_name: participant1
    hostname: participant1
    command: ["/app/main", "2"]
    networks:
      lan:
        ipv4_address: 172.18.0.3
    depends_on:
      - manager

  # participant2:
  #   build: .
  #   container_name: participant2
  #   hostname: participant2
  #   command: ["/app/main", "2"]
  #   networks:
  #     lan:
  #       ipv4_address: 172.18.0.4

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
