version: '3.8'

services:
  participant1:
    build: .
    container_name: participant1
    hostname: participant1
    command: ["/app/sleep_server", "172.18.0.11", "docker"]
    networks:
      lan:
        ipv4_address: 172.18.0.11

  participant2:
    build: .
    container_name: participant2
    hostname: participant2
    command: ["/app/sleep_server", "172.18.0.15", "docker"]
    networks:
      lan:
        ipv4_address: 172.18.0.15

  participant3:
    build: .
    container_name: participant3
    hostname: participant3
    command: ["/app/sleep_server", "172.18.0.14", "docker"]
    networks:
      lan:
        ipv4_address: 172.18.0.2

  participant4:
    build: .
    container_name: participant4
    hostname: participant4
    command: ["/app/sleep_server", "172.18.0.13", "docker"]
    networks:
      lan:
        ipv4_address: 172.18.0.13

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
